import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { exchangeAuthCode } from "@/lib/auth-codes";

export const dynamic = "force-dynamic";

const Body = z.object({
  // The auth code is generated by createAuthCode as exactly 32 bytes
  // base64url-encoded (= 43 chars, no padding).
  code: z.string().regex(/^[A-Za-z0-9_-]{43}$/),
  // The PKCE code_verifier per RFC 7636 §4.1: 43-128 chars from the
  // unreserved set.
  code_verifier: z.string().regex(/^[A-Za-z0-9_-]{43,128}$/),
});

export async function POST(req: NextRequest): Promise<NextResponse> {
  let body: unknown;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "invalid_json" }, { status: 400 });
  }
  const parsed = Body.safeParse(body);
  if (!parsed.success) {
    return NextResponse.json({ error: "invalid_body" }, { status: 400 });
  }
  const result = await exchangeAuthCode(parsed.data.code, parsed.data.code_verifier);
  if (!result) {
    return NextResponse.json({ error: "invalid_code" }, { status: 401 });
  }
  return NextResponse.json({ session_token: result.sessionId });
}
